### ISSUE TITLE
Tutorial correction

### ISSUE THREAD

**Issue by vodelerk** [hashicorp/learn-terraform-lifecycle-management#1]
in this tutorial: https://learn.hashicorp.com/tutorials/terraform/resource-lifecycle?in=terraform/state

in prevent resource deletion, the code provided for prevent_destroy has an extra '}' 

resource "aws_instance" "example" {
  ami                    = data.aws_ami.ubuntu.id
  instance_type          = "t2.micro"
  vpc_security_group_ids = [aws_security_group.sg_web.id]
  user_data              = <<-EOF
              #!/bin/bash
              echo "Hello, World" > index.html
              nohup busybox httpd -f -p 8080 &
              EOF
  tags = {
    Name          = "terraform-learn-state-ec2"
    drift_example = "v1"
  }
} <---------------------- this is the extra
+ lifecycle {
+   prevent_destroy = true
+ }
}

thank you.

**Comment by im2nguyen** [comment]
Thank you for reporting! We'll address it shortly :)

**Comment by im2nguyen** [comment]
This should be updated, thanks for reporting @vodelerk!
